name: github-ci



on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v1

      - name: build
        run: mvn compile
        with:
          java-version: '17'

  test:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v1

      - name: test
        run: mvn test
        with:
          java-version: '17'