name: github-ci

on:
  push:
    branches:
      - main

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: build
        run: mvn compile

  test:
    runs-on: ubuntu-latest

    needs:
      - setup
      - build

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: test
        run: mvn test