name: github-ci



on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: version
        run: mvn --version

      - name: git clone
        uses: actions/checkout@v1

      - name: build
        run: mvn compile

  test:
    runs-on: ubuntu-latest

    steps:
      - name: version
        run: mvn --version

      - name: git clone
        uses: actions/checkout@v1

      - name: test
        run: mvn test